In [2]:
import pandas as pd
df = pd.read_csv("application_train.csv")

df.head()

   SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0

[5 rows x 122 columns]

In [3]:
df.shape

(307511, 122)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [5]:
df['TARGET'].value_counts()

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [6]:
df.describe()

          SK_ID_CURR  ...  AMT_REQ_CREDIT_BUREAU_YEAR
count  307511.000000  ...               265992.000000
mean   278180.518577  ...                    1.899974
std    102790.175348  ...                    1.869295
min    100002.000000  ...                    0.000000
25%    189145.500000  ...                    0.000000
50%    278202.000000  ...                    1.000000
75%    367142.500000  ...                    3.000000
max    456255.000000  ...                   25.000000

[8 rows x 106 columns]

In [7]:
df.isnull().sum().sort_values(ascending=False).head(10)

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
NONLIVINGAPARTMENTS_AVG     213514
FONDKAPREMONT_MODE          210295
LIVINGAPARTMENTS_AVG        210199
LIVINGAPARTMENTS_MEDI       210199
LIVINGAPARTMENTS_MODE       210199
dtype: int64

In [8]:
threshold = len(df) * 0.5

df = df.loc[:, df.isnull().sum() < threshold]

df.shape

(307511, 81)

In [9]:
missing = df.isnull().sum()

In [10]:
cols_to_drop = missing[missing >= threshold].index
cols_to_drop

Index([], dtype='object')

In [11]:
df.select_dtypes(include='object').columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE',
       'EMERGENCYSTATE_MODE'],
      dtype='object')

In [12]:
for col in df.select_dtypes(include='object').columns:
    print(col, "->", df[col].nunique())

NAME_CONTRACT_TYPE -> 2
CODE_GENDER -> 3
FLAG_OWN_CAR -> 2
FLAG_OWN_REALTY -> 2
NAME_TYPE_SUITE -> 7
NAME_INCOME_TYPE -> 8
NAME_EDUCATION_TYPE -> 5
NAME_FAMILY_STATUS -> 6
NAME_HOUSING_TYPE -> 6
OCCUPATION_TYPE -> 18
WEEKDAY_APPR_PROCESS_START -> 7
ORGANIZATION_TYPE -> 58
EMERGENCYSTATE_MODE -> 2

In [13]:
df.select_dtypes(include='object').isnull().sum()

NAME_CONTRACT_TYPE                 0
CODE_GENDER                        0
FLAG_OWN_CAR                       0
FLAG_OWN_REALTY                    0
NAME_TYPE_SUITE                 1292
NAME_INCOME_TYPE                   0
NAME_EDUCATION_TYPE                0
NAME_FAMILY_STATUS                 0
NAME_HOUSING_TYPE                  0
OCCUPATION_TYPE                96391
WEEKDAY_APPR_PROCESS_START         0
ORGANIZATION_TYPE                  0
EMERGENCYSTATE_MODE           145755
dtype: int64

In [14]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna('Unknown')

In [15]:
df = pd.get_dummies(df)

In [16]:
df.shape

(307511, 197)

In [17]:
X = df.drop('TARGET', axis=1)
y = df['TARGET']

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
X_train.shape, X_test.shape

((246008, 196), (61503, 196))

In [21]:
X_train.isna().sum()

SK_ID_CURR                       0
CNT_CHILDREN                     0
AMT_INCOME_TOTAL                 0
AMT_CREDIT                       0
AMT_ANNUITY                     10
                                ..
ORGANIZATION_TYPE_University     0
ORGANIZATION_TYPE_XNA            0
EMERGENCYSTATE_MODE_No           0
EMERGENCYSTATE_MODE_Unknown      0
EMERGENCYSTATE_MODE_Yes          0
Length: 196, dtype: int64

In [22]:
X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

C:\Users\Precision5540\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [26]:
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56554
           1       0.40      0.00      0.01      4949

    accuracy                           0.92     61503
   macro avg       0.66      0.50      0.48     61503
weighted avg       0.88      0.92      0.88     61503

In [28]:
threshold = 0.3

y_pred_new = (y_proba >= threshold).astype(int)

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.92      0.99      0.95     56554
           1       0.33      0.07      0.12      4949

    accuracy                           0.91     61503
   macro avg       0.63      0.53      0.54     61503
weighted avg       0.88      0.91      0.89     61503

In [30]:
threshold = 0.2

y_pred_new = (y_proba >= threshold).astype(int)

In [31]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94     56554
           1       0.27      0.21      0.24      4949

    accuracy                           0.89     61503
   macro avg       0.60      0.58      0.59     61503
weighted avg       0.88      0.89      0.88     61503

In [32]:
threshold = 0.1

y_pred_new = (y_proba >= threshold).astype(int)

In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.95      0.76      0.85     56554
           1       0.17      0.56      0.26      4949

    accuracy                           0.75     61503
   macro avg       0.56      0.66      0.55     61503
weighted avg       0.89      0.75      0.80     61503